# Generated by Django 4.2.20 on 2025-04-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasker", "0003_remove_project_tasks_task_project"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workers",
                to="tasker.team",
            ),
        ),
    ]
